services:
  db:
    container_name: bookreviews_db
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: Hol@1234
      POSTGRES_DB: bookreviews
    volumes:
      - bookreviews_data:/var/lib/postgresql/data

  app:
    container_name: bookreviews_app
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://bookuser:Hol%401234@db:5432/bookreviews
      - ROCKET_PROFILE=docker
    depends_on:
      - db
    volumes:
      - .:/app

  populate:
    container_name: bookreviews_populate
    image: postgres:15
    depends_on:
      - app
    environment:
      PGPASSWORD: Hol@1234
    volumes:
      - ./populate_explicit_ids.sql:/populate.sql
    command: >
      sh -c "
        sleep 30 &&
        psql -h db -U bookuser -d bookreviews -f /populate.sql &&
        echo 'Base de datos poblada exitosamente'
      "

volumes:
  bookreviews_data: {}
