services:
  app:
    container_name: bookreviews_app_working
    build:
      context: .
      dockerfile: Dockerfile.working
    ports:
      - "8000:8000"
    environment:
      - ROCKET_PROFILE=docker
